/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:df9d12df-851b-4978-96c0-09585359076a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_LpHrTCPw6",
    "aws_user_pools_web_client_id": "1qaub6q5erjj66haojgod9i1j9",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://fznvjs7gzfhonb5i6szpd4awx4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wz57g5enlvep5dpmwrjzwvofbq",
    "aws_user_files_s3_bucket": "awsproject8323bb13017a4477bcd0711301be9dc229bad-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
